### ISSUE TITLE
Kind remind

### ISSUE THREAD

**Issue by waltonfuture** [mengcaopku/Continual-LLaVA#1]
Your paper uses the iclr camera ready version, which is incorrect.

**Comment by mengcaopku** [comment]
Thanks for reminding. We'll fix it asap.

**Comment by waltonfuture** [comment]
:) 
I have another question: what version of llava do you use? Llava 1, 1.5, 1.6 or onevision?
And we know that llava-onevision(the newest llava) combine almost every domains of data in the joint training stage, including Docvqa, chartvqa mentioned in your paper. Can we find other domains that llava-onevision has not focused on? This may be helpful in practical usage.

**Comment by mengcaopku** [comment]
Thanks for your suggestions. We use Llava 1.5 to avoid your mentioned data overlapping issue in the domain-incremental setting. However, since current large vision languge models use extensive pre-training and instruction-tuning datasets, the data overlapping issue is unavoidable. That is why we set the dataset-incremental setting, which evaluates the continual learning in LVLMs in a more practical scenario.

**Comment by waltonfuture** [comment]
Thanks for your response!

**Comment by mengcaopku** [comment]
We have updated the arXiv version to be the pre-print format. Thanks for your reminding again.
